namespace Domain.Enums
{
    public static class PermissionEnum
    {
        public enum Permission
        {
            CreateProduct,
            UpdateProduct,
            DeleteProduct,
            ReadProduct,
            DeleteImage,
            CreateBrand,
            UpdateBrand,
            DeleteBrand,
            ReadBrand,
            CreateBanner,
            UpdateBanner,
            DeleteBanner,
            ReadBanner,
            CreatePost,
            UpdatePost,
            DeletePost,
            ReadPost,
            CreateSlide,
            UpdateSlide,
            DeleteSlide,
            ReadSlide,
            CreateCategory,
            UpdateCategory,
            DeleteCategory,
            ReadCategory,
            UpdateOrder,
            ReadOrder,
            ChangeOrderStatus,
            UpdateUser,
            LockUser,
            CreateRole,
            UpdateRole,
            DeleteRole,
            AssignRole,
            ReadRole,
            ReadPermission,
            UploadProductImage,
            ReadUser,
            CreateUser,
            UpdateUserAvatar,
        }
    }
}
