namespace Domain.Enums
{
    public static class PermissionEnum
    {
        public enum Permission
        {
            CreateProduct,
            UpdateProduct,
            DeleteProduct,
            ReadProduct,
            DeleteImage,
            CreateBrand,
            UpdateBrand,
            DeleteBrand,
            CreateBanner,
            UpdateBanner,
            DeleteBanner,
            ReadBanner,
            CreatePost,
            UpdatePost,
            DeletePost,
            readPost,
            CreateSlide,
            UpdateSlide,
            DeleteSlide,
            readSlide,
            CreateCategory,
            UpdateCategory,
            DeleteCategory,
            ReadCategory,
            UpdateOrder,
            ChangeOrderStatus,
            UpdateUser,
            LockUser,
            CreateRole,
            UpdateRole,
            DeleteRole,
            AssignRole,
        }
    }
}
